//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace konfirence.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int Id { get; set; }
        public int NameEvent { get; set; }
        public System.DateTime DateStart { get; set; }
        public int Days { get; set; }
        public string Activity1 { get; set; }
        public int Day { get; set; }
        public System.TimeSpan TimeStart { get; set; }
        public int IdMod { get; set; }
        public Nullable<int> Jury1 { get; set; }
        public Nullable<int> Jury2 { get; set; }
        public Nullable<int> Jury3 { get; set; }
        public Nullable<int> Jury4 { get; set; }
        public Nullable<int> Jury5 { get; set; }
        public int Winner { get; set; }
    
        public virtual Events Events { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual Users Users2 { get; set; }
        public virtual Users Users3 { get; set; }
        public virtual Users Users4 { get; set; }
        public virtual Users Users5 { get; set; }
        public virtual Users Users6 { get; set; }
    }
}
